---
# tasks file for haproxy-podman
- name: install haproxy systemd unit file
  template:
    src: ../templates/haproxy-container.service.j2
    dest: /etc/systemd/system/haproxy-container.service
  notify:
    - systemd enable reload
  tags: haproxy

- name: install haproxy config
  template:
    src: ../templates/haproxy-container.conf.j2
    dest: /etc/haproxy-container.conf
  notify:
    - restart haproxy
  tags: haproxy

#- name: systemd haproxy enabled
#  systemd:
#    name: haproxy-container 
#    state: started
#    enabled: yes
#  tags: haproxy

#- name: check syntax haproxy apiVersion
#  shell: |
#    podman run -it --rm -v /etc/haproxy-container.conf:/usr/local/etc/haproxy --name haproxy-syntax-check haproxy:2.0 haproxy -c -f /usr/local/etc/haproxy:
